[README REVIEW] Adiciona explicação sobre .only
betrybe/sd-0x-project-starwars-planets-search-rubric pull request #6
Opened 2021-07-02 13:42 UTC by Ludilly

Adiciona explicação sobre .only

Adiciona explicação sobre teste ser em RTL

Adiciona imagens

2021-07-14 13:48 UTC, vitrokb approved these changes

2021-07-14 15:10 UTC, danielfasanaro approved these changes

2021-07-19 19:50 UTC, renatofreire requested changes

2021-07-19 19:50 UTC, renatofreire commented on README.md
> +Se o requisito pedir "crie um botão e adicione o id de teste (ou `data-testid`) com o valor `my-action`, você pode criar:
@Ludilly  legal ter essa explicação sobre o RTL :) 
Na minha sugestão eu mantive as mesmas informações, só reescrevi para um formato mais parecido com o formato do restante do documento.
Acha que faz sentido essa alteração?

```suggestion
Neste projeto utilizamos a [React Testing Library (RTL)](https://testing-library.com/docs/react-testing-library/intro) para execução dos testes unitários.

Em alguns dos [Requisitos do projeto](#requisitos-do-projeto) será pedido que você coloque o atributo `data-testid` nos elementos HTML. Isso acontece pois a RTL utiliza esse atributo para poder verificar a solução proposta.

Por exemplo, se o requisito pedir "crie um botão e adicione o id de teste (ou `data-testid`) com o valor `my-action`", você poderá criar:
```

2021-07-19 19:50 UTC, renatofreire commented on README.md
> +Afim de verificar a solução proposta, você pode executar todos os testes unitários localmente, basta executar:
Aqui é a mesma lógica do comentário de cima :D :arrow_up:  

```suggestion
O atributo `data-testid="my-action"` servirá para a React Testing Library identificar o elemento e, dessa forma, será possível realizar os testes unitários focados no comportamento da aplicação.

**Importante:** Em alguns requisitos, utilizamos o método `getByRole` para poder selecionar os elementos de forma semântica. Portanto atente-se às instruções de cada requisito. Por exemplo, se o requisito pedir explicitamente um button, você deverá utilizar exatamente esse elemento.

Para verificar se seu projeto atende aos requisitos, você pode executar todos os testes unitários localmente, executando o comando:
```

2021-07-20 11:54 UTC, renatofreire approved these changes

2021-07-20 11:56 UTC, merged